version: '3.4'

services:
  postgres_image:
    image: postgres:latest
    ports:
      - 5432:5432
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: virtu-trade-db
volumes:
  db_volume: 